spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${URL}:3306/emb?serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}

  main:
    allow-bean-definition-overriding: true

  my-env:
    first: ${FIRST_MALLANG_ENV}
    second: ${SECOND_MALLANG_ENV}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}


  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-exp: ${JWT_ACCESS_EXP}
      refresh-exp: ${JWT_REFRESH_EXP}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace