spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emb?serverTimezone=Asia/Seoul
    username: {username}
    password: {password}

  main:
    allow-bean-definition-overriding: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}


  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-exp: ${JWT_ACCESS_EXP}
      refresh-exp: ${JWT_REFRESH_EXP}

  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true